### ISSUE TITLE
Example data

### ISSUE THREAD

**Issue by hanshanmengqi** [wangjr03/FLAMINGO#15]
Hi,
Thank you a lot for this powerful tool.
But now I met a case that I can't download example .hic data (4DNFI1UEG1HD.hic). As shown below.
Could you please help me?

Thank you in advance.

![image](https://github.com/wangjr03/FLAMINGO/assets/93769611/f101f70a-d10c-4ac6-8617-65d66c7600f1)

Han

**Comment by JiaxinYangJX** [comment]
Thanks for using our software! I guess you need to register an account in 4DN before you download the demo dataset.

In addition, we are currently collecting all the feedback and reorganizing our tools. We will release a more user-friendly version later this year.

**Comment by hanshanmengqi** [comment]
Hi @JiaxinYangJX ,
I would like to know if you have released a new version.
Best,
Han

**Comment by JiaxinYangJX** [comment]
Hi @hanshanmengqi 
Thanks for using our tools!
We just released a lite version of FLAMINGO, which is faster, more memory-efficient, and more user-friendly. We fixed the majority of bugs and hope the new version could help. Below is the link.
https://github.com/JiaxinYangJX/FLAMINGOrLite
