### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by sdjin87** [wangjr03/FLAMINGO#2]
`> install_github('wangjr03/FLAMINGO/FLAMINGOr')`
`Downloading GitHub repo wangjr03/FLAMINGO@master
from URL https://api.github.com/repos/wangjr03/FLAMINGO/zipball/master
Installation failed: 404: Not Found (404)`

I have problem with installation
How can i fix it?

**Comment by haowang0508** [comment]
> 
Hi,
It seems like by default you are downloading the package from the master branch instead of the head branch.
Please try install_github('wangjr03/FLAMINGO/FLAMINGOr',ref='HEAD').

**Comment by sdjin87** [comment]
Thank you for your cooperation.

and I have one more question 

Error in checkForRemoteErrors(val): one node produced an error: 'from' must be a finite number
Traceback:

1. flamingo.main_func_large(hic_data_low = "/mnt/gmi-l1/_90.User_Data/sdjin87/Hi-C/aln_chm13/a2780cis/aligned/inter_30.hic", 
 .     file_format = "hic", domain_res = 1000000, frag_res = 5000, 
 .     chr_size = 248387328, chr_name = "chr1", normalization = "KR", 
 .     downsampling_rates = 0.75, lambda = 10, max_dist = 0.01, 
 .     nThread = 10, n_row = 30000)
2. flamingo.reconstruct_structure(sw = downsampling_rates, lambda = lambda, 
 .     max_dist = max_dist, nThread = nThread)
3. parallel::parSapply(cl, 1:n, function(x) {
 .     flamingo.reconstruct_structure_wraper(x, sw, lambda, max_dist, 
 .         nThread = 1)
 . })
4. parLapply(cl = cl, X = as.list(X), fun = FUN, ..., chunk.size = chunk.size)
5. do.call(c, clusterApply(cl = cl, x = splitList(X, nchunks), fun = lapply, 
 .     FUN = fun, ...), quote = TRUE)
6. clusterApply(cl = cl, x = splitList(X, nchunks), fun = lapply, 
 .     FUN = fun, ...)
7. staticClusterApply(cl, fun, length(x), argfun)
8. checkForRemoteErrors(val)
9. stop("one node produced an error: ", firstmsg, domain = NA)

I don't know why occurred these error. 
I think our server resource is enough.(80thread / 768GB mem / CentOS7)
even that, I had no problem with another sample. 
Please. Do you know how can i fix it?

**Comment by haowang0508** [comment]
Hi, 
Glad to know you have downloaded it and the code works for the other sample. For the error you mentioned, my best guess is that this sample has some special issues. Could you try:

```
file <- dir('./Domain_data/')
# please double check to make sure N represents the largest index of the domain
N <- max(as.numeric(sapply(strsplit(file,"_|[.]"),function(x){x[3]})))
for(idx in 1:N){
flamingo.reconstruct_structure_wraper(idx,sw=0.75,lambda=10,max_dist=0.01,nThread=1)
}
```

This code block will go through the domains individually and pinpoint the one that caused the problem (when it throws an error, please check the value of idx, which is the index of the domain). Please send the PD and IF files (can be found in ../Domain_data) of the identified domain to wangha73.at.msu.edu so I can further check it.

**Comment by sdjin87** [comment]
Thank you 
I will check and send you.
What is mgcv version you use.

**Comment by haowang0508** [comment]
> 
We tested on mgcv 1.8-24.
