### ISSUE TITLE
environments for FLAMINGO in conda 

### ISSUE THREAD

**Issue by feefee20** [wangjr03/FLAMINGO#7]
Hello,

Thanks for the useful tool!
I am trying to add your tool in conda.
Would you please provide all dependencies/environments to stabilize your tool in conda? 
Thanks for your help. 
 
--------------------------------
Here's my environment in conda:

Python 3.7.0 | packaged by conda-forge | (default, Nov 12 2018, 20:15:55) 
[GCC 7.3.0] :: Anaconda, Inc. on linux

R version 3.5.1 (2018-07-02)

--------------------------------

**Comment by feefee20** [comment]
Hello, what version of mgcv is available for R3.5.1 ? 
The current mgcv seems to work in >= R3.6.0 (https://cran.r-project.org/web/packages/mgcv/index.html).

**Comment by feefee20** [comment]
Hi again, 

I am trying to learn the tool by following your tutorial with the following commands and .hic file downloaded from your server: '4DNFI1UEG1HD.hic'.

It seemed to work for a while and stopped without any notice. Would you please help me out to fix the issue?
Thanks again.


-----------------------------------------------------
>> cat Flamingo.R 
library(FLAMINGOr)
library(GenomicFeatures)
library(Matrix)
setwd("/home/usr/test/")
all_size <- getChromInfoFromUCSC("hg38")
chr_name='1'
chr_name = as.numeric(chr_name)
chr_size = all_size[chr_name,2]
chr_name <- paste0('chr',chr_name)
res = flamingo.main_func_large(hic_data_low='4DNFI1UEG1HD.hic',
                       file_format='hic',
                         domain_res=1e6,frag_res=5e3,
                         chr_size=chr_size,
                         chr_name=chr_name,
                         normalization='KR',
                         downsampling_rates=0.75,
                         lambda=10,max_dist=0.01,nThread=10,n_row=30000)

-------------------------------------
>> cat R-Rout 

Loading required package: BiocGenerics
Loading required package: parallel

Attaching package: ‘BiocGenerics’

The following objects are masked from ‘package:parallel’:

    clusterApply, clusterApplyLB, clusterCall, clusterEvalQ,
    clusterExport, clusterMap, parApply, parCapply, parLapply,
    parLapplyLB, parRapply, parSapply, parSapplyLB

The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs

The following objects are masked from ‘package:base’:

    anyDuplicated, append, as.data.frame, basename, cbind, colMeans,
    colnames, colSums, dirname, do.call, duplicated, eval, evalq,
    Filter, Find, get, grep, grepl, intersect, is.unsorted, lapply,
    lengths, Map, mapply, match, mget, order, paste, pmax, pmax.int,
    pmin, pmin.int, Position, rank, rbind, Reduce, rowMeans, rownames,
    rowSums, sapply, setdiff, sort, table, tapply, union, unique,
    unsplit, which, which.max, which.min

Loading required package: S4Vectors
Loading required package: stats4

Attaching package: ‘S4Vectors’

The following object is masked from ‘package:base’:

    expand.grid

Loading required package: IRanges
Loading required package: GenomeInfoDb
Loading required package: GenomicRanges
Loading required package: AnnotationDbi
Loading required package: Biobase
Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.


Attaching package: ‘Matrix’

The following object is masked from ‘package:S4Vectors’:

    expand

Download and preprocess the 'chrominfo' data frame ... OK
[1] "Contact map is too large, large matrix mod is on"
[1] "Dividing domains..."
[1] "Processing Fragments..."
[1] "caching datasets..."
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
[1] "Reconstructing backbones..."
Loading required package: nlme

Attaching package: ‘nlme’

The following object is masked from ‘package:IRanges’:

    collapse

This is mgcv 1.8-30. For overview type 'help("mgcv-package")'.
[1] "Reconstructing intra-domain structures..."
[1] "Assembling structures..."
[1] "Reading substructures..."
[1] 0.9025089
[1] 0.89027
[1] 0.9137103
[1] 0.9374543
[1] 0.9477833
[1] 0.953385
[1] 0.9551066
[1] 0.9559585
[1] 0.9561721
[1] 0.9564341
[1] 0.9562101
[1] 0.9563441
[1] 0.9564717
[1] 0.9564755
---------------------------------------------------------

Our system is under:

PRETTY_NAME="Debian GNU/Linux bookworm/sid"
NAME="Debian GNU/Linux"
VERSION_CODENAME=bookworm

**Comment by JiaxinYangJX** [comment]
Thanks for using our software!

I guess there might be version conflicts with the imported packages. Below are the specific versions we used. Let us know if it works or not. Thanks!

strawr_0.0.9
mgcv_1.8-24
data.table_1.14.2
Matrix_1.2-14

**Comment by feefee20** [comment]
Hello, thanks for leaving your comments. 

I tried to run with same input file using the specific versions you used. It was stopped in the same step:
Would be there any other possibilities?
--------------------------------------
Loading required package: BiocGenerics
Loading required package: parallel

Attaching package: ‘BiocGenerics’

The following objects are masked from ‘package:parallel’:

    clusterApply, clusterApplyLB, clusterCall, clusterEvalQ,
    clusterExport, clusterMap, parApply, parCapply, parLapply,
    parLapplyLB, parRapply, parSapply, parSapplyLB

The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs

The following objects are masked from ‘package:base’:

    anyDuplicated, append, as.data.frame, basename, cbind, colMeans,
    colnames, colSums, dirname, do.call, duplicated, eval, evalq,
    Filter, Find, get, grep, grepl, intersect, is.unsorted, lapply,
    lengths, Map, mapply, match, mget, order, paste, pmax, pmax.int,
    pmin, pmin.int, Position, rank, rbind, Reduce, rowMeans, rownames,
    rowSums, sapply, setdiff, sort, table, tapply, union, unique,
    unsplit, which, which.max, which.min

Loading required package: S4Vectors
Loading required package: stats4

Attaching package: ‘S4Vectors’

The following object is masked from ‘package:base’:

    expand.grid

Loading required package: IRanges
Loading required package: GenomeInfoDb
Loading required package: GenomicRanges
Loading required package: AnnotationDbi
Loading required package: Biobase
Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.


Attaching package: ‘Matrix’

The following object is masked from ‘package:S4Vectors’:

    expand

Download and preprocess the 'chrominfo' data frame ... OK
[1] "Contact map is too large, large matrix mod is on"
[1] "Dividing domains..."
[1] "Processing Fragments..."
[1] "caching datasets..."
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
x being coerced from class: matrix to data.table
[1] "Reconstructing backbones..."
Loading required package: nlme

Attaching package: ‘nlme’

The following object is masked from ‘package:IRanges’:

    collapse

This is mgcv 1.8-24. For overview type 'help("mgcv-package")'.
[1] "Reconstructing intra-domain structures..."
[1] "Assembling structures..."
[1] "Reading substructures..."
[1] 0.8948703
[1] 0.8873293
[1] 0.9090315
[1] 0.9331877
[1] 0.9445207
[1] 0.9496162
[1] 0.9521453
[1] 0.9535208
[1] 0.9533331
[1] 0.9537537
[1] 0.9540145
[1] 0.9539554
[1] 0.9544871
[1] 0.9538467
[1] 0.9537651
[1] 0.9542682
[1] 0.9539849
[1] 0.9543945
[1] 0.9537225
[1] 0.9541244
[1] 0.9539704
[1] 0.9547069
[1] 0.9537147
[1] 0.9535678
[1] 0.9542396
[1] 0.953753
[1] 0.9542073
[1] 0.9537703
[1] 0.9536681
[1] 0.9542657
[1] 0.9538538
[1] 0.9542356
[1] 0.9536596
[1] 0.9542218
[1] 0.9538604
[1] 0.9545839
[1] 0.9537431
[1] 0.9536594
[1] 0.9542836
[1] 0.9537856
[1] 0.9541401
[1] 0.9537089
[1] 0.9538501
[1] 0.9540793
[1] 0.9545435
[1] 0.9540005
[1] 0.9537947
[1] 0.954292
[1] 0.9539477
[1] 0.9544799
[1] 0.9537465
[1] 0.9538839
[1] 0.9541428
[1] 0.9543467
[1] 0.9542681
[1] 0.9539082
[1] 0.9542826
[1] 0.9540526
[1] 0.9545228
[1] 0.9538347
[1] 0.9537045
[1] 0.9543104
[1] 0.9538473
[1] 0.9543116
[1] 0.9536972
[1] 0.953979
[1] 0.9540262
[1] 0.9546933
[1] 0.9538353
[1] 0.9536791
[1] 0.9542338
[1] 0.953831
[1] 0.9543182
[1] 0.9537921
[1] 0.953709
[1] 0.954267
[1] 0.9539183
[1] 0.9542961
[1] 0.9536923
[1] 0.9542224
[1] 0.9538936
[1] 0.9546177
[1] 0.9537461
[1] 0.9536442
[1] 0.954293
[1] 0.9537741
[1] 0.954136
[1] 0.9537202
[1] 0.9537915
[1] 0.9541292
[1] 0.9543364
[1] 0.9541758
[1] 0.9538586
[1] 0.9543355
[1] 0.9540273
[1] 0.954521
[1] 0.9537627
[1] 0.9538989
[1] 0.9541521
[1] 0.954354
[1] 0.9542992
[1] 0.9539195
[1] 0.9542797
[1] 0.954063
[1] 0.9545454
[1] 0.9538409
[1] 0.9536836
[1] 0.9543252
[1] 0.9538122
[1] 0.9542873
[1] 0.9537004
[1] 0.9539002
[1] 0.9540757
[1] 0.9545299
[1] 0.9540552
[1] 0.9538984
[1] 0.9542503
[1] 0.9540754
[1] 0.9545151
[1] 0.953808
[1] 0.9538528
[1] 0.9542044
[1] 0.9542915
[1] 0.9543642
[1] 0.9538691
[1] 0.9543221
[1] 0.9540091
[1] 0.9545936
[1] 0.9537961
[1] 0.9537028
[1] 0.954287
[1] 0.9538296
[1] 0.954216
[1] 0.953749
[1] 0.9538069
[1] 0.9541542
[1] 0.9543266
[1] 0.9542158
[1] 0.9538635
[1] 0.9543392
[1] 0.9540249
[1] 0.9545341
[1] 0.9537707
[1] 0.9538627
[1] 0.9541841
[1] 0.954206
[1] 0.9543615
[1] 0.9538475
[1] 0.9542538
[1] 0.9539999
[1] 0.9545552
[1] 0.9538409
[1] 0.9536102
[1] 0.9543582
[1] 0.9537377
[1] 0.9541998
[1] 0.953696
[1] 0.9537733
[1] 0.9541499
[1] 0.9541036
[1] 0.9542334
[1] 0.9537971
[1] 0.9542974
[1] 0.9539374
[1] 0.9544189
[1] 0.9538227
[1] 0.9537069
[1] 0.9543
[1] 0.9538738
[1] 0.9542997
[1] 0.9536895
[1] 0.9541213
[1] 0.9539445
[1] 0.9547085
[1] 0.9537017
[1] 0.9536084
[1] 0.954262
[1] 0.953764
[1] 0.9541841
[1] 0.9537542
[1] 0.9537269
[1] 0.9542137
[1] 0.954035
[1] 0.9542885
[1] 0.9537407
[1] 0.954333
[1] 0.9538856
[1] 0.9544806
[1] 0.9537774
[1] 0.9537316
[1] 0.954266
[1] 0.9538782
[1] 0.9542246
[1] 0.9537275
[1] 0.9540206
[1] 0.954011 
--------------------------------------------------------------------------------

**Comment by JiaxinYangJX** [comment]
Hi, thanks for reaching out. Based on the output file, I think your code has been run successfully. Only thing is that you need to save the `res` data.

**Comment by feefee20** [comment]
Thanks for checking. All set! Thanks again!
